# Generated by Django 3.0.10 on 2021-05-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, verbose_name='Enter  the categroy name')),
                ('no_of_quest', models.IntegerField(verbose_name='Enter the no. of questions in this quiz')),
                ('time', models.IntegerField(verbose_name='Enter the time  (only minutes) for quiz')),
                ('basic_min_score', models.IntegerField(verbose_name='minimum no. of correct answers required for Beginners courses')),
                ('basic_max_score', models.IntegerField(verbose_name='maximum no. of correct answers required for Beginners courses')),
                ('medium_min_score', models.IntegerField(verbose_name='minimum no. of correct answers required for Intermediate courses')),
                ('medium_max_score', models.IntegerField(verbose_name='maximum  no. of correct answers required for Intermediate courses')),
                ('advance_min_score', models.IntegerField(verbose_name='minimum no. of correct answers required for Advance courses')),
                ('advance_max_score', models.IntegerField(verbose_name='maximum no. of correct answers required for Advance courses')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Enter the question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Select the category')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('BEGINNERS', 'BEGINNERS'), ('INTERMEDIATE', 'INTERMEDIATE'), ('ADVANCE', 'ADVANCE')], default='BASIC', max_length=500, verbose_name='Select the level of course')),
                ('course_name', models.CharField(max_length=500, verbose_name='Enter the course name')),
                ('course_link', models.URLField(verbose_name='Add the course weblink url')),
                ('course_imageurl', models.URLField(blank=True, null=True, verbose_name='Add the course thumbnail URL')),
                ('course_image', models.ImageField(null=True, upload_to='', verbose_name='OR  upload the thumbnail')),
                ('course_price', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the price if course is paid otherwise leave it empty')),
                ('course_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enter the mai site owner name like coursera, khan academy, udemy, swayam etc')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Select the category of course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=4000, verbose_name='Enter the answers')),
                ('correct_answer', models.BooleanField(verbose_name='Tick the one which is correct')),
                ('question_text1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question')),
            ],
        ),
    ]
