# Generated by Django 3.0.10 on 2021-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210516_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='OR  upload the thumbnail'),
        ),
    ]
